language: go
go:
  - 1.12.1

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      install:
        - pip install --user awscli
      before_script:
        - sh build.sh
      # script:
        # - aws cloudformation
