language: go
go:
  - 1.12.1

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      install:
        - pip install --user awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set default.region ap-northeast-1
      script:
        - sh build.sh
        - sh deploy.sh

cache:
  directories:
    - /home/travis/gopath/pkg
