language: go
go:
  - "1.13"

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      install:
        - pip install --user awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set default.region ap-northeast-1
      script:
        - go test ./test/...
      after_script:
        - make
        - sh deploy.sh

cache:
  directories:
    - /home/travis/gopath/pkg
