AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  BotVerificationToken:
    Type: String
  BotAccessToken:
    Type: String
  SearchEngineId:
    Type: String
  PlaceApiKey:
    Type: String
  CustomSearchApiKey:
    Type: String

Globals:
  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 5

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: botmeshi-content-bucket

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: botmeshi-lambda-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
               - Effect: "Allow"
                 Action:
                   - logs:*
                   - lambda:InvokeFunction
                 Resource: "*"
               - Effect: "Allow"
                 Action:
                  - s3:PutObject
                  - s3:GetObject
                 Resource: !Sub "${S3Bucket.Arn}/*"

  EventLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - LambdaRole
    Properties:
      FunctionName: botmeshi-event
      Handler: event
      CodeUri: ./built/event.zip
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          BOT_VERIFICATION_TOKEN: !Ref BotVerificationToken
          BOT_ACCESS_TOKEN: !Ref BotAccessToken
      Events:
        Post:
          Type: Api
          Properties:
            Path: /event
            Method: Post
            RestApiId: !Ref Api

  EventLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - EventLambdaFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref EventLambdaFunction]]

  InteractiveLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - LambdaRole
    Properties:
      FunctionName: botmeshi-interactive
      Handler: interactive
      CodeUri: ./built/interactive.zip
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          BOT_VERIFICATION_TOKEN: !Ref BotVerificationToken
          INVOKE_LAMBDA_ARN: !GetAtt InvokeSearchLambdaFunction.Arn
      Events:
        Post:
          Type: Api
          Properties:
            Path: /interactive
            Method: Post
            RestApiId: !Ref Api

  InteractiveLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - InteractiveLambdaFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref InteractiveLambdaFunction]]

  InvokeSearchLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - LambdaRole
    Properties:
      FunctionName: botmeshi-invoke-search
      Handler: invoke-search
      Timeout: 60
      CodeUri: ./built/invoke-search.zip
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          BOT_ACCESS_TOKEN: !Ref BotAccessToken
          SEARCH_ENGINE_ID: !Ref SearchEngineId
          PLACE_API_KEY: !Ref PlaceApiKey
          CUSTOM_SEARCH_API_KEY: !Ref CustomSearchApiKey

  InvokeSearchLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - InvokeSearchLambdaFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join ["/", ["/aws/lambda", !Ref InvokeSearchLambdaFunction]]


  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: botmeshi-api
      StageName: botmeshi
      Cors:
        AllowMethods: "'POST'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: 2.0
        info:
          version: 2019-08-24T09:42:02Z
          title: botmeshi-api
        basePath: "/botmeshi"
        schemes:
          - "https"
        paths:
          /event:
            post:
              produces:
                - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                uri: !Join
                  - "/"
                  - - "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions"
                    - !GetAtt EventLambdaFunction.Arn
                    - "invocations"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: "mock"
          /interactive:
            post:
              produces:
                - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
              x-amazon-apigateway-integration:
                uri: !Join
                  - "/"
                  - - "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions"
                    - !GetAtt InteractiveLambdaFunction.Arn
                    - "invocations"
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"
            options:
              consumes:
                - "application/json"
              produces:
                - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                passthroughBehavior: "when_no_match"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                type: "mock"
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"
